import Data_Import
import Models
import numpy as np
import os
import h5py
from tensorflow.keras.preprocessing.image import ImageDataGenerator


# load the data

#base_dir = '/Documents/MIBI_Data/CS230/test_run/'
base_dir = '/home/ubuntu/SuperMIBI/data/test_run/'

if os.path.isfile(base_dir + 'x_cropped.h5'):
    print('loading previously saved data')
    # read in data to avoid reprocessing on subsequent analysis
    x_data_reload = h5py.File(base_dir + 'x_cropped.h5', 'r')
    y_data_reload = h5py.File(base_dir + 'y_cropped.h5', 'r')
    x_data_cropped = x_data_reload['x_vals'][:]
    y_data_cropped = y_data_reload['y_vals'][:]

else:
    print('no previous data data detected. Loading from directory')
    x_dirs = ['Point7/', 'Point9/', 'Point11/']
    y_dirs = ['Point8/', 'Point10/', 'Point12/']
    dir_suffix = 'TIFs/'

    x_dirs = [base_dir + x + dir_suffix for x in x_dirs]
    y_dirs = [base_dir + y + dir_suffix for y in y_dirs]
    channels = os.listdir(x_dirs[0])
    bad_bois = ['Background.tif', 'Fe.tif', 'Ta.tif', 'Au.tif', 'Ca.tif', 'totalIon.tif', 'Na.tif', 'C.tif', 'Si.tif']
    channels = [x for x in channels if x not in bad_bois]

    x_data, y_data = Data_Import.load_dataset(x_dirs, y_dirs, channels)

    # crop data
    print('cropping the data')
    x_data_cropped = Data_Import.crop_dataset(dataset=x_data, crop_size=128, stride_fraction=0.333)
    y_data_cropped = Data_Import.crop_dataset(dataset=y_data, crop_size=128, stride_fraction=0.333)

    # save data for quicker loading next time

    print('saving data for faster loading next time')
    h5_x_cropped = h5py.File(base_dir + 'x_cropped.h5', 'w')
    h5_y_cropped = h5py.File(base_dir + 'y_cropped.h5', 'w')

    h5_x_cropped.create_dataset('x_vals', data=x_data_cropped)
    h5_y_cropped.create_dataset('y_vals', data=y_data_cropped)

    h5_x_cropped.close()
    h5_y_cropped.close()

    chans = np.array(channels)
    np.save(base_dir + 'chan_names', chans)


# create train and test split
print('Generating train/test split')
np.random.seed(seed=1)
choo_choo_idx = np.random.binomial(n=1, p=0.01, size=x_data_cropped.shape[0])
x_train, x_test = x_data_cropped[choo_choo_idx, :, :, :], x_data_cropped[~choo_choo_idx, :, :, :]
y_train, y_test = y_data_cropped[choo_choo_idx, :, :, :], y_data_cropped[~choo_choo_idx, :, :, :]
print('x_train shape is {}. y_train_shape is {}.'.format(x_train.shape, y_train.shape)) 

# include only a subset of channels
if os.path.isfile(base_dir + 'chan_names.npy'):
    print('using previously saved channel names for subsetting')
    chans = np.load(base_dir + 'chan_names.npy')
else:
    print('using currently generated channel names')

keepers = ['dsDNA.tif', 'H3K9Ac.tif']
keep_idx = np.isin(chans, keepers)
print('analyzing the following channels: {}'.format(chans[keep_idx]))

x_train, x_test = x_train[:, :, :, keep_idx], x_test[:, :, :, keep_idx]
y_train, y_test = y_train[:, :, :, keep_idx], y_test[:, :, :, keep_idx]
print('new x_train shape is {}. new y_train_shape is {}.'.format(x_train.shape, y_train.shape)) 


# create model
model_1 = Models.SuperMIBI_1((128, 128, np.sum(keep_idx)))
model_1.compile(optimizer='adam', loss='mse', metrics=['accuracy'])


# initializer data augmentation iterator
datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        zca_epsilon=1e-06,  # epsilon for ZCA whitening
        rotation_range=180,  # randomly rotate images in the range (degrees, 0 to 180)
        # randomly shift images horizontally (fraction of total width)
        width_shift_range=0.,
        # randomly shift images vertically (fraction of total height)
        height_shift_range=0.,
        shear_range=0.,  # set range for random shear
        zoom_range=0.,  # set range for random zoom
        channel_shift_range=0.,  # set range for random channel shifts
        # set mode for filling points outside the input boundaries
        fill_mode='nearest',
        cval=0.,  # value used for fill_mode = "constant"
        horizontal_flip=True,  # randomly flip images
        vertical_flip=True,  # randomly flip images
        # set rescaling factor (applied before any other transformation)
        rescale=None,
        # set function that will be applied on each input
        preprocessing_function=None,
        # image data format, either "channels_first" or "channels_last"
        data_format='channels_last',
        # fraction of images reserved for validation (strictly between 0 and 1)
        validation_split=0.0)


# Fit the model on the batches generated by datagen.flow().
print('training the model')
model_1.history = model_1.fit_generator(datagen.flow(x_train, y_train, batch_size=32), epochs=4)

# evaluate model
print('evaluating the model')
preds = model_1.evaluate(x=x_test, y=y_test)
print()
print("Training accuracy: {}".format(np.round(model_1.history.history['acc'], 2)))
print("Loss = " + str(preds[0]))
print("Test Accuracy = " + str(preds[1]))
